### ISSUE TITLE
Deploy new version

### ISSUE THREAD

**Issue by vikeri** [lelandrichardson/react-native-mock#104]
I noticed there are some commits that have not been released, my tests are failing due to this and I would prefer not to fork the library. Is there a reason that a new release is not published? Anything I can do to help with releasing a new version?

**Comment by RealOrangeOne** [comment]
damn it! I forgot to do a deploy last night. I'll start doing one right now!

**Comment by RealOrangeOne** [comment]
Deployed `0.2.7`
