### ISSUE TITLE
Publish latest version to NPM

### ISSUE THREAD

**Issue by michael-ar** [lelandrichardson/react-native-mock#109]
Hello,

Had a PR which was merged last week, any chance you could publish the latest version to NPM?
CI tests are currently failing.

Thank you

**Comment by RealOrangeOne** [comment]
once #114 is merged, I will do a deploy. CI tests on master are now passing too

**Comment by RealOrangeOne** [comment]
After seeing dependency issues with that PR, am publishing now

**Comment by michael-ar** [comment]
thanks man!
