### ISSUE TITLE
Incompatibility with React 15.4.0

### ISSUE THREAD

**Issue by joemckie** [lelandrichardson/react-native-mock#111]
Your dependency on `react-addons-perf` is breaking with React 15.4.0.

Can this be updated?

**Comment by RealOrangeOne** [comment]
Yes, that should be a very simple fix!

**Comment by joemckie** [comment]
@RealOrangeOne I'm taking a look into a PR now. Is there a reason why the versions are explicitly required using `=` rather than `^`?

**Comment by RealOrangeOne** [comment]
for devDependancies yes, it allows for more reproducable tests. For the main dependancies no, Think I messed up a find/replace

**Comment by gaearon** [comment]
I'd recommend using Jest for testing React Native instead. That's what we use at FB, and we maintain it.

**Comment by gaearon** [comment]
<s>I'd recommend using Jest for testing React Native instead. That's what we use at FB, and we maintain it.</s>
(Never mind my comment, wrong thread)

**Comment by Richard-Cao** [comment]
The same error:
```
Error: Cannot find module 'react/lib/ReactPerf'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/richardcao/workspace/reading/node_modules/react-addons-perf/index.js:1:18)
```
## Version:
- react-native-mock@0.2.8
- mocha@3.1.2
- react@15.4.1
- react-dom@15.4.1
- react-addons-test-utils@15.4.1
- react-native@0.38.0

**Comment by joemckie** [comment]
@Richard-Cao check out the PR (#114). Looks like RN has a stable 0.38.0 release now so we can try and get this fixed!
