### ISSUE TITLE
Upgrade to react 15.4

### ISSUE THREAD

**Issue by ofirdagan** [lelandrichardson/react-native-mock#117]
Hey, Even though I saw you upgraded to support react 15.4 in version 0.2.8.

When I run `npm info react-native-mock` I still get react version 15.1.0

Can u please check?

Thanks!

**Comment by ofirdagan** [comment]
The current work around I did for now is adding a `postinstall` step in my `package.json` which deletes the `node_modules` directory inside `react-native-mock` Then installing its dependencies explicitly with version 15.4.1

Please let me know if you fix this so I can remove my work around.

**Comment by RealOrangeOne** [comment]
This fix has been made, in #114. Will hopefully release early next week
