### ISSUE TITLE
Release 0.2.8 is not compatible with react 15.4.0

### ISSUE THREAD

**Issue by antseburova** [lelandrichardson/react-native-mock#124]
Hi,
I moved to react 15.4.0 and found out that the last release of react-native-mock (v0.2.8) is not compatible with it due to one of its dependencies. I am experiencing an issue with react-addons-perf (v15.1.0), which is not compatible with react 15.4.0.  I have noticed that there is actually some work already done in the master branch to make react-native-mock compatible with  react 15.4.0 . Could you please tell me when  you are going to officially release the latest changes?

Thank you

**Comment by RealOrangeOne** [comment]
Oh dear. Yes I shall do a release later on today in that case!

**Comment by antseburova** [comment]
It would be great. Thank you very much!

**Comment by RealOrangeOne** [comment]
Released `0.3.0`. Please upgrade and let me know if it works!

**Comment by antseburova** [comment]
Thank you very much for the release. However, I get the following error when I try to run my tests:
"Cannot find module 'underscore'". Do I have to install underscore? I didn't have to do that for the previous versions.

**Comment by RealOrangeOne** [comment]
Have fixed issue, hopefully. Please try `0.3.1`

**Comment by antseburova** [comment]
Perfect! Works as expected. Thank you very much for your instant help!
