### ISSUE TITLE
Instance() does not work with mount()

### ISSUE THREAD

**Issue by jnak** [lelandrichardson/react-native-mock#16]
I'm not sure as well if it's expected

I've added a repro in this commit:
https://github.com/jnak/enzyme-rn-ref-repro/commit/fc3876931c9e5c7dafd5c54769cc60a456765b9d

Thanks!

**Comment by iyawnis** [comment]
What exactly you mean its not working? It is working fine for me

```
    let wrapper = mount(<Foo/>);
    let instance = wrapper.instance();
    instance.addTask(something);
```

**Comment by jnak** [comment]
```
class MyComponent extends React.Component {
  render() {
    return (
      <View>
        <Subcomponent />
        <Subcomponent 
          testProp={true}
          ref={(ref) => this.second = ref}
        />
      </View>
    );
  }
}

class Subcomponent extends React.Component {
  render() {
    <Text>
      Hello
    </Text>
  }
}

const wrapper = mount(<MyComponent />);
expect(wrapper.find(Subcomponent).instance()).to.be.instanceOf(Subcomponent);
```

This fails with:

> TypeError: Cannot read property 'getInstance' of null
>      at ReactWrapper.instance (node_modules/enzyme/build/ReactWrapper.js:143:30)
>     at Context.<anonymous> (MyComponent-test.js:22:39)

**Comment by RealOrangeOne** [comment]
The `React.Component` used in react-native-mock comes direct from ReactJS. This looks to be more of a problem with enzyme than react-native-mock. Try testing this using HTML components, is the result the same?

**Comment by jnak** [comment]
My bad. Apparently instance() only works a wrapper that is also a root instance. Thanks for the help!
