### ISSUE TITLE
NavigationExperimental support

### ISSUE THREAD

**Issue by aksonov** [lelandrichardson/react-native-mock#22]
Reducers could be tested without any problem, is it possible to import them without changes?

**Comment by rlau1115** [comment]
@aksonov - Just opened an issue related to testing your react-native-router-flux module: [here](https://github.com/lelandrichardson/react-native-mock/issues/23)

Have you been able to run tests with your plugin in any projects?

**Comment by aksonov** [comment]
@rlau1115 I'm currently working on 3.0 release with unit testing and NavigationExperimental API support. Current version of RNRF has no unit tests and now i'm adding unit testing for new release.

**Comment by sattaman** [comment]
+1

**Comment by RealOrangeOne** [comment]
This is currently being looked into in #34 and #48

**Comment by RealOrangeOne** [comment]
#48 has now been merged and released
