### ISSUE TITLE
It'd better to render something instead of null

### ISSUE THREAD

**Issue by andrey-skl** [lelandrichardson/react-native-mock#33]
We render null everywhere
https://github.com/lelandrichardson/react-native-mock/blob/master/src/components/View.js#L281

Just 

``` javascript
render() {
  return <div {...props}>{props.children}</div>;
}
```

Should be enough in most cases. Otherwise there is no proper way to check props and childten.

**Comment by RealOrangeOne** [comment]
I have a PR open (#20) that fixes this for text components.  Other components will be possible, but marginally harder.

**Comment by iyawnis** [comment]
Using enzyme you can access both Children and props, https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md

**Comment by RealOrangeOne** [comment]
The best way i found at the moment to get the content from a rendered component is to access it's `children` prop using `instance.prop('children');`

**Comment by lelandrichardson** [comment]
This library is intended to work with a shallow renderer. It should not matter what `View` renders, it should only matter what higher order components rendering a `<div>` here is meaningless.

This API should work fine with shallow. Are you using something different?

cc @RealOrangeOne

**Comment by andrey-skl** [comment]
@lelandrichardson actually looks like you're right and it should be enough to be able to get props via enzyme (which I use)

**Comment by RealOrangeOne** [comment]
With the library only meant to be run using enzymes `shallow` render (or similar), no the content of what's rendered doesnt really matter. In future I think it might be worth rendering relevant information (especially for elements like listviews etc). But I think for now, just access the `children` prop as shown above.

**Comment by lelandrichardson** [comment]
for non-native components like `ListView`, it might make sense to render something other than `null`. Keep in mind though, you should be testing what your component renders, and relying on understanding what ListView's render tree looks like inside of your tests may not be the best idea. Regardless, it's a much more reasonable thing to do in that case versus doing so for `<Text>` or `<View>`.

**Comment by RealOrangeOne** [comment]
Closing issue for now. Definately something that'd be great for someone to look into! Especially for things that render off function props such as `ListView`.

**Comment by ghost** [comment]
For a shallow wrapper, you can call a wrapper.instance().props.propName to get the value of respective prop.
