### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by DanielMSchmidt** [lelandrichardson/react-native-mock#5]
Hi there,

First of all thanks for this idea, it is exactly the point I am currently struggling with testing my react native application. I just wanted to ask if you have a project on github which uses this mock, I would love to see it in action somewhere.

Have a nice day!

**Comment by lelandrichardson** [comment]
not yet, per se.... but keep an eye on this repo: https://github.com/lelandrichardson/enzyme-example-react-native :)

**Comment by lelandrichardson** [comment]
as well as this PR landing: https://github.com/airbnb/enzyme/pull/159

in that PR you can see some documentation added for getting enzyme working with react-native

**Comment by DanielMSchmidt** [comment]
Awesome, thanks for the feedback. Enzyme is also one of the libraries I planned to try out the next days, so that fits perfectly.
