### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by hassankhan** [lelandrichardson/react-native-mock#57]
I ran the install command as per the README:

``` bash
npm ERR! peerinvalid The package react@15.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-mock@0.2.2 wants react@*
npm ERR! peerinvalid Peer react-native@0.26.2 wants react@15.0.2
```

Not really sure why it's being like that, could you possibly remove `react` as a `peerDependency`?

Thanks for creating this, by the way 😄

**Comment by hassankhan** [comment]
I should have probably mentioned my use-case, I'm trying to write tests for a React Native plugin, so I'm saving it as a `devDependency` in the plugin's `package.json`. In an ideal scenario, I'd rather not install either `react` or `react-native, only this mock package.

**Comment by RealOrangeOne** [comment]
Hi, this looks like youre trying to install the wrong version of react. You have to install 15.0.2 to work with react-native 0.26.

**Comment by hassankhan** [comment]
I haven't specified _any_ version of `react` OR `react-native` to install, I only wanted to install this package.

**Comment by RealOrangeOne** [comment]
you will need to install `react` for this package to work, the version must be the same as the one required for the latest version of `react-native`, in this case, `15.0.2`. The easiest way to do this would be to add react-native as a dev-dep to your project, then it installs everything you need

**Comment by hassankhan** [comment]
Ahh okay, thanks for the pointer. I tried installing `react-native` as a `devDependency` (`npm install react-native@0.26`), that didn't work either. Turns out I needed to install both:

``` bash
$ npm install react@15.0.2 react-native@^0.26 --save-dev
```

**Comment by RealOrangeOne** [comment]
The mock is designed to run on react-native projects, therefore they'll need `react` and `react-native` installed. I should probably work on adding them as specific dependancies, so this doesnt happen in the future

**Comment by sibelius** [comment]
this line https://github.com/lelandrichardson/react-native-mock/blob/master/package.json#L43 will cause the same problem on RN27 that depends on react@^15.1.0 instead of react@15.0.2

**Comment by RealOrangeOne** [comment]
Yes, this is by design. I shall update these versions in the deploy I do later today. `react-native-mock` is only designed to work with the most recent version of `react-native`

**Comment by sibelius** [comment]
\o/ let's keep on the bleeding edge
