### ISSUE TITLE
Node haste throws when building app

### ISSUE THREAD

**Issue by ColCh** [lelandrichardson/react-native-mock#64]
It happends when I try to build with dev deps (e.g. `react-native-mock` and `react-native` with `react` are inside of `./node_modules`)

Just take a look on this log:

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: AutoFocusUtils
  Paths: /foo/node_modules/react-native-mock/node_modules/react/lib/AutoFocusUtils.js collides with /foo/node_modules/react/lib/AutoFocusUtils.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: AutoFocusUtils
  Paths: /foo/node_modules/react-native-mock/node_modules/react/lib/AutoFocusUtils.js collides with /foo/node_modules/react/lib/AutoFocusUtils.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/foo/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:160:15)
    at /foo/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:125:25
:app:bundleReleaseJsAndAssets FAILED
```

 `@providesModule` is a Node haste thing, but I can't find real docs for it. It's needed for build step, but does `react-native-mock` really needs these module ids? This module is used in testing purposes, and with this declarations we forced to remove this module every build ...

May be just remove those declarations and everything will be fine? `react-native-mock` is used by `jest.setMock` or as mock in `__mocks__` directory, so I think, `@providesModule` really is not needed.

**Comment by RealOrangeOne** [comment]
We aren't actually using `node-haste` in `react-native-mock`. At what point is this error occuring? At install time, package time, or test time?

**Comment by ColCh** [comment]
On build time.
This error happends if `react-native-mock` is remain in `./node_modules`.
To succesfully build my app, I should remove this module by hand.

I'm **forced** to keep my devDeps and deps in same dir, because:
1. It's CI cache
2. because of npm bug: npm/npm#12654 

Really, I can send you a PR which removes those `@providesModule`, it's not that hard. Just tell me, whether this module id is useful for you or not. 

(I think, it's useless, in case of testing util, which is not used at build time)

**Comment by RealOrangeOne** [comment]
Sure! Submit a PR and i'll take a look.

**Comment by dieguitoweb** [comment]
+1

**Comment by ColCh** [comment]
May be related to #58 as well

**Comment by AshCoolman** [comment]
Out of curiosity, @ColCh Does `npm shrinkwrap` fail, citing `node-haste` as a problem?

**Comment by ColCh** [comment]
@AshCoolman no.
We are using RN v0.26 (React v15.0) so I will check for RNM v0.2.2:

``` sh
➜  PROJ git:(master) ✗ npm i -S react-native-mock@0.2.2
- react-addons-test-utils@15.1.0 node_modules/react-native-mock/node_modules/react-addons-test-utils
PROJ@0.0.1 /Users/ColCh/Documents/Workspace/PROJ
└─┬ react-native-mock@0.2.2 
  ├── react-addons-create-fragment@15.0.2 
  ├── react-addons-linked-state-mixin@15.0.2 
  ├── react-addons-perf@15.0.2 
  ├── react-addons-pure-render-mixin@15.0.2 
  └── react-addons-update@15.0.2 

➜  PROJ git:(master) ✗ npm shrinkwrap                  
wrote npm-shrinkwrap.json
```

Works just fine.

But if I install RNM@0.2.3 (for React@15.1), it will fail (of course):

``` sh
➜  PROJ git:(master) ✗ npm shrinkwrap 
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/ColCh/.nvm/versions/node/v5.10.1/bin/node" "/Users/ColCh/.nvm/versions/node/v5.10.1/bin/npm" "shrinkwrap"
npm ERR! node v5.10.1
npm ERR! npm  v3.9.0

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: react@^15.1.0, required by react-addons-create-fragment@15.1.0
npm ERR! peer invalid: react@^15.1.0, required by react-addons-linked-state-mixin@15.1.0
npm ERR! peer invalid: react@^15.1.0, required by react-addons-perf@15.1.0
npm ERR! peer invalid: react@^15.1.0, required by react-addons-pure-render-mixin@15.1.0
npm ERR! peer invalid: react@^15.1.0, required by react-addons-update@15.1.0
npm ERR! peer invalid: react@^15.1.0, required by react-addons-test-utils@15.1.0
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ColCh/Documents/PROJ/npm-debug.log
```

**Comment by ColCh** [comment]
Hm, I realized that my meaning was wrong! I found **no** `@providesModule`. 

And, see this log?

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: AutoFocusUtils
  Paths: /foo/node_modules/react-native-mock/node_modules/react/lib/AutoFocusUtils.js collides with /foo/node_modules/react/lib/AutoFocusUtils.js
```

`react-native-mock/node_modules/react` - that was the root of the trouble.

It's solving by moving away react dependency from package.json.
And it is already! 
This commit bring this brilliant solution: https://github.com/lelandrichardson/react-native-mock/commit/545b880d59a0bd742c5303448a8546c759006cf5

So, consider this particular case of doubled `@providesModule` directives solved!

That commit was introduced first in `v0.2.2` of `react-native-mock`. 

Hey, @RealOrangeOne, I will close this issue since it's resolved. Please take a look into #58 , may be it's about  `@providesModule` too. And it's being resolved since **v0.2.2**

Thanks! 👍

**Comment by RealOrangeOne** [comment]
I guess one thing that could be done to improve this would be remove react as a dependancy, and specify the version needed in a peer dependancy. If i'm right, that should fix the problem?

**Comment by ColCh** [comment]
yes, it seems that error from node-haste was because of local react installation in react-native-mock/node_modules folder.
