### ISSUE TITLE
TypeError: _reactNative.Platform.select is not a function

### ISSUE THREAD

**Issue by bhaskarmurthy** [lelandrichardson/react-native-mock#70]
Running a test on a component that uses `Platform.select`, and getting a test exception:

`
TypeError: _reactNative.Platform.select is not a function
    at Object.<anonymous> (Fonts.js:20:33)
    at Module._compile (module.js:409:26)
`

`react-native-mock@0.2.3`

**Comment by RealOrangeOne** [comment]
This is because the `Platform.select` API hasnt been mocked yet. There is currently an open PR (#61) that is solving this. However he hasnt responded for a while, so feel free to submit your own!

**Comment by evollu** [comment]
since the fix has been merged, can you bump the version?

**Comment by RealOrangeOne** [comment]
Yes, I shall try and do a deploy later today
