### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by vikeri** [lelandrichardson/react-native-mock#83]
Just wondering when the next version will be published to npm? Since I'll be using this with Travis I'd prefer not to have to pull master. Using NavigationExperimental so I need the newer version.

**Comment by sibelius** [comment]
u can specify a commit number instead of master

**Comment by vikeri** [comment]
@sibelius I did that but it failed since the folder `build` generated from `npm run build` was not present. I had to clone it and run `npm link` which then built the `build`-folder.

**Comment by sibelius** [comment]
I though prepublish script https://github.com/lelandrichardson/react-native-mock/blob/master/package.json#L7 would handle the generation of build

we need to fix this to enable install from github directly

**Comment by RealOrangeOne** [comment]
I have been thinking of some kind of `react-native@next`  that would auto deploy from travis. But yes, I shall push out a new release later today

**Comment by sibelius** [comment]
@RealOrangeOne what about install directly from github?

**Comment by RealOrangeOne** [comment]
that would work, but currently the app will require a build step unless youre using something like babel-node.

**Comment by mortik** [comment]
Why not just add the build dir to the repo?

**Comment by RealOrangeOne** [comment]
because commiting the built source is a nightmare for PR review, and generally a bad idea.

**Comment by mortik** [comment]
I would like to disaggree ^^ but thats only my opinion. 
An automated build step and push to npm after the ci is green seems to be the solution then ;)

**Comment by RealOrangeOne** [comment]
Version `0.2.6` has been released. Will be working on an 'unstable' release schedule soon! Closing this issue for now!
