### ISSUE TITLE
`done` is not a function

### ISSUE THREAD

**Issue by taylor1791** [lelandrichardson/react-native-mock#92]
React native has a non-standard extension to `Promise`. It adds a done method that throws any uncaught errors. Unless I am mistaken, I don't believe `react-native-mock` adds this. Are there plans to do this?

**Comment by RealOrangeOne** [comment]
I did not know react-native did this, so no there arent any plans for this. Can you provide some examples of this, as i'm not exactly sure what it's use is.

**Comment by taylor1791** [comment]
I discovered this in the [AsyncStorage Example](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AsyncStorageExample.js#L45). More research shows that using `done` is no longer necessary after [0fa8d16](https://github.com/facebook/react-native/commit/0fa8d162c15591be0e3fb40a8a1e8730043824e8) fixed [ !facebook/react-native/4045](https://github.com/facebook/react-native/issues/4045).

So, if people are on a recent version of react-native they can remove it without any harm. For this reason, I don't need it anyone. In theory, if someone is on a sufficiently old version of react-native, they may need this.

If you think this is something react-native-mock does not need, feel free to close the issue.

**Comment by RealOrangeOne** [comment]
Seeing as it's now been fixed. I think it's fine not to support it. Generally we only try to support the most recent version of react-native
